"""Reader for OGC 3D Tiles output (tileset.json + .glb tiles).

Provides metadata access and tile enumeration from a 3D Tiles tileset
generated by ``TileGenerator3D(output_format="3dtiles")``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


class TileReader3DTiles:
    """Read OGC 3D Tiles from disk.

    Parameters
    ----------
    tileset_path : Path or str
        Path to the ``tileset.json`` file.
    """

    def __init__(self, tileset_path: Path | str) -> None:
        self._path = Path(tileset_path)
        self._base_dir = self._path.parent
        with open(self._path) as f:
            self._tileset = json.load(f)

    @property
    def metadata(self) -> dict[str, Any]:
        """Full tileset.json content."""
        return self._tileset

    @property
    def asset(self) -> dict[str, Any]:
        """Asset info (version, etc.)."""
        return self._tileset.get("asset", {})

    @property
    def geometric_error(self) -> float:
        """Root geometric error."""
        return self._tileset.get("geometricError", 0.0)

    @property
    def root(self) -> dict[str, Any]:
        """Root tile node."""
        return self._tileset.get("root", {})

    def _collect_tiles(
        self,
        node: dict[str, Any],
        depth: int = 0,
    ) -> list[dict[str, Any]]:
        """Recursively collect all tile nodes with their depth."""
        result = []
        if "content" in node:
            result.append({
                "uri": node["content"]["uri"],
                "depth": depth,
                "boundingVolume": node.get("boundingVolume"),
                "geometricError": node.get("geometricError", 0.0),
            })
        for child in node.get("children", []):
            result.extend(self._collect_tiles(child, depth + 1))
        return result

    def all_tiles(self) -> list[dict[str, Any]]:
        """List all tiles in the tileset (flattened)."""
        return self._collect_tiles(self.root)

    def tiles_at_depth(self, target_depth: int) -> list[dict[str, Any]]:
        """List tiles at a specific tree depth (0 = root)."""
        return [t for t in self.all_tiles() if t["depth"] == target_depth]

    def read_tile(self, uri: str) -> bytes | None:
        """Read a GLB tile by its URI (relative to tileset.json).

        Returns GLB bytes or None if the file doesn't exist.
        """
        tile_path = self._base_dir / uri
        if not tile_path.exists():
            return None
        return tile_path.read_bytes()

    def tile_count(self) -> int:
        """Total number of tiles with content."""
        return len(self.all_tiles())

    def max_depth(self) -> int:
        """Maximum depth in the tile tree."""
        tiles = self.all_tiles()
        if not tiles:
            return 0
        return max(t["depth"] for t in tiles)
