"""TileReader3D — decode .mvt3 files back to features.

Reads tiles generated by TileGenerator3D and can reconstruct
a MicroJSON FeatureCollection from a zoom level.
"""

from __future__ import annotations

import json
import struct
from pathlib import Path
from typing import Any

from geojson_pydantic import Point, LineString, Polygon

from ..model import MicroFeature, MicroFeatureCollection
from .projector3d import CartesianProjector3D
from .proto import microjson_3d_tile_pb2 as pb

# Reverse GeomType mapping
_GEOM_TYPE_NAMES = {
    0: "Unknown",
    1: "Point3D",
    2: "LineString3D",
    3: "Polygon3D",
    4: "PolyhedralSurface",
    5: "TIN",
}


def _decode_commands(geometry: list[int]) -> list[tuple[int, list[tuple[int, int]]]]:
    """Decode MVT command stream to list of (cmd, [(dx, dy), ...])."""
    result = []
    i = 0
    while i < len(geometry):
        cmd_int = geometry[i]
        cmd = cmd_int & 0x7
        count = cmd_int >> 3
        i += 1

        if cmd == 7:  # ClosePath
            result.append((7, []))
            continue

        points = []
        for _ in range(count):
            if i + 1 >= len(geometry):
                break
            sx = geometry[i]
            sy = geometry[i + 1]
            # Zigzag decode
            dx = (sx >> 1) ^ (-(sx & 1))
            dy = (sy >> 1) ^ (-(sy & 1))
            points.append((dx, dy))
            i += 2
        result.append((cmd, points))

    return result


def _decode_z(z_deltas: list[int]) -> list[int]:
    """Decode delta-encoded Z coordinates."""
    if not z_deltas:
        return []
    result = [z_deltas[0]]
    for i in range(1, len(z_deltas)):
        result.append(result[-1] + z_deltas[i])
    return result


def _decode_tags(
    tag_indices: list[int], keys: list[str], values: list[Any],
) -> dict[str, Any]:
    """Decode key/value tag pairs from indices."""
    tags = {}
    for i in range(0, len(tag_indices), 2):
        if i + 1 >= len(tag_indices):
            break
        key_idx = tag_indices[i]
        val_idx = tag_indices[i + 1]
        if key_idx < len(keys) and val_idx < len(values):
            tags[keys[key_idx]] = values[val_idx]
    return tags


def _extract_value(pb_value: Any) -> Any:
    """Extract Python value from protobuf Value message."""
    which = pb_value.WhichOneof("kind")
    if which is None:
        return None
    return getattr(pb_value, which)


def decode_tile(data: bytes) -> list[dict]:
    """Decode a .mvt3 tile from protobuf bytes.

    Returns a list of decoded feature dicts per layer.
    """
    tile = pb.Tile()
    tile.ParseFromString(data)

    layers = []
    for layer in tile.layers:
        keys = list(layer.keys)
        values = [_extract_value(v) for v in layer.values]

        features = []
        for feat in layer.features:
            mesh_pos_bytes = bytes(feat.mesh_positions)
            mesh_idx_bytes = bytes(feat.mesh_indices)

            if mesh_pos_bytes:
                # Indexed mesh path (TIN/PolyhedralSurface)
                # Return raw bytes — consumer uses struct/numpy/torch
                # Reconstruct xy/z for backward-compat consumers
                n_floats = len(mesh_pos_bytes) // 4
                n_verts = n_floats // 3
                floats = struct.unpack(f"<{n_floats}f", mesh_pos_bytes)
                xy_points = [
                    (int(floats[i * 3]), int(floats[i * 3 + 1]))
                    for i in range(n_verts)
                ]
                z_abs = [int(floats[i * 3 + 2]) for i in range(n_verts)]
            else:
                # Ring-based decode path (Point, Line, Polygon)
                commands = _decode_commands(list(feat.geometry))
                abs_x, abs_y = 0, 0
                xy_points = []

                for cmd, points in commands:
                    if cmd == 7:  # ClosePath — don't add duplicate point
                        continue
                    for dx, dy in points:
                        abs_x += dx
                        abs_y += dy
                        xy_points.append((abs_x, abs_y))

                z_abs = _decode_z(list(feat.geometry_z))

            features.append({
                "id": feat.id,
                "type": feat.type,
                "type_name": _GEOM_TYPE_NAMES.get(feat.type, "Unknown"),
                "tags": _decode_tags(list(feat.tags), keys, values),
                "xy": xy_points,
                "z": z_abs,
                "mesh_positions": mesh_pos_bytes,
                "mesh_indices": mesh_idx_bytes,
                "radii": list(feat.radii) if feat.radii else [],
            })

        layers.append({
            "name": layer.name,
            "version": layer.version,
            "extent": layer.extent,
            "extent_z": layer.extent_z,
            "features": features,
        })

    return layers


class TileReader3D:
    """Read 3D vector tiles from disk.

    Parameters
    ----------
    tilejson_path : Path or str
        Path to the TileJSON 3D metadata file.
    """

    def __init__(self, tilejson_path: Path | str) -> None:
        self._path = Path(tilejson_path)
        self._base_dir = self._path.parent
        with open(self._path) as f:
            self._meta = json.load(f)

    @property
    def metadata(self) -> dict:
        return self._meta

    def read_tile(
        self, z: int, x: int, y: int, d: int,
    ) -> list[dict] | None:
        """Read and decode a single tile.

        Returns decoded layers or None if tile doesn't exist.
        """
        tile_path = self._base_dir / str(z) / str(x) / str(y) / f"{d}.mvt3"
        if not tile_path.exists():
            return None
        return decode_tile(tile_path.read_bytes())

    def tiles_at_zoom(self, z: int) -> list[tuple[int, int, int, int, list[dict]]]:
        """Read all tiles at a given zoom level.

        Returns list of (z, x, y, d, decoded_layers).
        """
        results = []
        z_dir = self._base_dir / str(z)
        if not z_dir.exists():
            return results

        for x_dir in sorted(z_dir.iterdir()):
            if not x_dir.is_dir():
                continue
            for y_dir in sorted(x_dir.iterdir()):
                if not y_dir.is_dir():
                    continue
                for tile_file in sorted(y_dir.iterdir()):
                    if tile_file.suffix == ".mvt3":
                        d_val = int(tile_file.stem)
                        layers = decode_tile(tile_file.read_bytes())
                        results.append((
                            z, int(x_dir.name), int(y_dir.name), d_val, layers,
                        ))
        return results

    def tiles2microjson(
        self,
        z: int,
    ) -> MicroFeatureCollection:
        """Reconstruct a MicroFeatureCollection from tiles at a zoom level.

        Transforms tile-local integer coordinates back to world coordinates
        using the bounds from the TileJSON metadata.
        """
        bounds3d = self._meta.get("bounds3d")
        if not bounds3d or len(bounds3d) < 6:
            bounds3d = [0.0, 0.0, 0.0, 1.0, 1.0, 1.0]

        proj = CartesianProjector3D(tuple(bounds3d))
        n = 1 << z  # tiles per axis at this zoom

        features: list[MicroFeature] = []
        tiles = self.tiles_at_zoom(z)

        for tz, tx, ty, td, layers in tiles:
            for layer in layers:
                extent = layer.get("extent", 4096)
                extent_z = layer.get("extent_z", 4096)

                for feat in layer.get("features", []):
                    xy_pts = feat["xy"]
                    z_vals = feat["z"]

                    if not xy_pts:
                        continue

                    # Convert tile-local integers → normalized [0,1]
                    coords_3d = []
                    for i, (ix, iy) in enumerate(xy_pts):
                        nx = (ix / extent + tx) / n
                        ny = (iy / extent + ty) / n
                        nz_val = (z_vals[i] / extent_z + td) / n if i < len(z_vals) else 0.0
                        # Unproject to world
                        wx, wy, wz = proj.unproject(nx, ny, nz_val)
                        coords_3d.append((wx, wy, wz))

                    geom_type = feat.get("type", 0)
                    tags = feat.get("tags", {})

                    # Reconstruct GeoJSON geometry
                    if geom_type == 1:  # POINT3D
                        if len(coords_3d) == 1:
                            geom = Point(
                                type="Point",
                                coordinates=list(coords_3d[0]),
                            )
                        else:
                            continue  # skip multi-point for now
                    elif geom_type == 2:  # LINESTRING3D
                        if len(coords_3d) >= 2:
                            geom = LineString(
                                type="LineString",
                                coordinates=[list(c) for c in coords_3d],
                            )
                        else:
                            continue
                    else:
                        # Polygon/TIN/PolyhedralSurface — store as Polygon
                        if len(coords_3d) >= 3:
                            ring = [list(c) for c in coords_3d]
                            if ring[0] != ring[-1]:
                                ring.append(ring[0])
                            geom = Polygon(
                                type="Polygon",
                                coordinates=[ring],
                            )
                        else:
                            continue

                    features.append(MicroFeature(
                        type="Feature",
                        geometry=geom,
                        properties=tags if tags else {},
                    ))

        return MicroFeatureCollection(
            type="FeatureCollection",
            features=features,
        )
