"""Microjson using manual MuDM pydantic models,
but autogenerated GeoJSON models."""
from typing import Optional, Union
from pydantic import BaseModel, StrictInt, StrictStr
from geojson.Feature import GeojsonFeature
from geojson.FeatureCollection import GeojsonFeaturecollection
from geojson.Geometry import GeojsonGeometry
from geojson.GeometryCollection import GeojsonGeometrycollection
from mudm.model import Multiscale


class GeoJSONAuto(BaseModel):
    """The root object of a GeoJSON file"""

    __root__: Union[
        GeojsonFeature,
        GeojsonFeaturecollection,
        GeojsonGeometry,
        GeojsonGeometrycollection,
    ]


class MuDMFeature(GeojsonFeature):
    """A MuDM feature, which is a GeoJSON feature with additional
    metadata"""

    multiscale: Optional[Multiscale]
    ref: Optional[Union[StrictStr, StrictInt]]


class MuDMFeatureCollection(GeojsonFeaturecollection):
    """A MuDM feature collection, which is a GeoJSON feature
    collection with additional metadata"""

    multiscale: Optional[Multiscale]


class MuDMAuto(BaseModel):
    """The root object of a MuDM file"""

    __root__: Union[
        MuDMFeature, MuDMFeatureCollection,
        GeojsonGeometry, GeojsonGeometrycollection
    ]
