"""SWC ↔ MicroJSON conversion utilities.

SWC is the standard format for neuron morphology data. This module provides
bidirectional conversion between SWC files and MicroJSON NeuronMorphology
geometry types.
"""

from __future__ import annotations

from typing import Union

from geojson_pydantic import Feature, MultiLineString

from .model import MicroFeature, NeuronMorphology, SWCSample


def swc_to_microjson(swc_path: str) -> MicroFeature:
    """Parse an SWC file and return a MicroJSON Feature with NeuronMorphology
    geometry.

    Args:
        swc_path: Path to the SWC file.

    Returns:
        A MicroFeature wrapping a NeuronMorphology geometry.
    """
    samples: list[SWCSample] = []
    with open(swc_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 7:
                continue
            samples.append(
                SWCSample(
                    id=int(parts[0]),
                    type=int(parts[1]),
                    x=float(parts[2]),
                    y=float(parts[3]),
                    z=float(parts[4]),
                    r=float(parts[5]),
                    parent=int(parts[6]),
                )
            )

    geometry = NeuronMorphology(type="NeuronMorphology", tree=samples)
    return MicroFeature(type="Feature", geometry=geometry, properties={})


def microjson_to_swc(feature: Union[Feature, MicroFeature]) -> str:
    """Convert a MicroJSON Feature with NeuronMorphology geometry to SWC text.

    Args:
        feature: A Feature whose geometry is a NeuronMorphology.

    Returns:
        SWC-formatted string.
    """
    geom = feature.geometry
    if not isinstance(geom, NeuronMorphology):
        raise TypeError(
            f"Expected NeuronMorphology geometry, got {type(geom).__name__}"
        )

    lines = ["# SWC file generated by MicroJSON"]
    lines.append("# id type x y z r parent")
    for s in geom.tree:
        lines.append(f"{s.id} {s.type} {s.x} {s.y} {s.z} {s.r} {s.parent}")
    return "\n".join(lines) + "\n"


def swc_to_linestring3d(swc_path: str) -> MultiLineString:
    """Convert an SWC file to a MultiLineString for skeleton rendering.

    Each edge in the SWC tree becomes a 2-point 3D line segment.

    Args:
        swc_path: Path to the SWC file.

    Returns:
        A MultiLineString where each line is a parent→child edge.
    """
    feature = swc_to_microjson(swc_path)
    geom = feature.geometry
    assert isinstance(geom, NeuronMorphology)

    # Build id → sample lookup
    by_id = {s.id: s for s in geom.tree}

    # Collect edges: for each non-root node, draw a line from parent to child
    lines: list[list[tuple[float, float, float]]] = []
    for s in geom.tree:
        if s.parent == -1:
            continue
        parent = by_id[s.parent]
        lines.append([
            (parent.x, parent.y, parent.z),
            (s.x, s.y, s.z),
        ])

    return MultiLineString(type="MultiLineString", coordinates=lines)
