# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microjson_3d_tile.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17microjson_3d_tile.proto\x12\x10microjson.tile3d\"\xcc\x05\n\x04Tile\x12,\n\x06layers\x18\x03 \x03(\x0b\x32\x1c.microjson.tile3d.Tile.Layer\x1a\xad\x01\n\x05Value\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x15\n\x0b\x66loat_value\x18\x02 \x01(\x02H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x13\n\tint_value\x18\x04 \x01(\x03H\x00\x12\x14\n\nuint_value\x18\x05 \x01(\x04H\x00\x12\x14\n\nsint_value\x18\x06 \x01(\x12H\x00\x12\x14\n\nbool_value\x18\x07 \x01(\x08H\x00\x42\x06\n\x04kind\x1a\xc5\x01\n\x07\x46\x65\x61ture\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x04tags\x18\x02 \x03(\rB\x02\x10\x01\x12-\n\x04type\x18\x03 \x01(\x0e\x32\x1f.microjson.tile3d.Tile.GeomType\x12\x14\n\x08geometry\x18\x04 \x03(\rB\x02\x10\x01\x12\x16\n\ngeometry_z\x18\x05 \x03(\x11\x42\x02\x10\x01\x12\x11\n\x05radii\x18\x06 \x03(\x02\x42\x02\x10\x01\x12\x16\n\x0emesh_positions\x18\x07 \x01(\x0c\x12\x14\n\x0cmesh_indices\x18\x08 \x01(\x0c\x1a\xb6\x01\n\x05Layer\x12\x0f\n\x07version\x18\x0f \x01(\r\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x30\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\x1e.microjson.tile3d.Tile.Feature\x12\x0c\n\x04keys\x18\x03 \x03(\t\x12,\n\x06values\x18\x04 \x03(\x0b\x32\x1c.microjson.tile3d.Tile.Value\x12\x0e\n\x06\x65xtent\x18\x05 \x01(\r\x12\x10\n\x08\x65xtent_z\x18\x06 \x01(\r\"e\n\x08GeomType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07POINT3D\x10\x01\x12\x10\n\x0cLINESTRING3D\x10\x02\x12\r\n\tPOLYGON3D\x10\x03\x12\x15\n\x11POLYHEDRALSURFACE\x10\x04\x12\x07\n\x03TIN\x10\x05\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microjson_3d_tile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_TILE_FEATURE'].fields_by_name['tags']._options = None
  _globals['_TILE_FEATURE'].fields_by_name['tags']._serialized_options = b'\020\001'
  _globals['_TILE_FEATURE'].fields_by_name['geometry']._options = None
  _globals['_TILE_FEATURE'].fields_by_name['geometry']._serialized_options = b'\020\001'
  _globals['_TILE_FEATURE'].fields_by_name['geometry_z']._options = None
  _globals['_TILE_FEATURE'].fields_by_name['geometry_z']._serialized_options = b'\020\001'
  _globals['_TILE_FEATURE'].fields_by_name['radii']._options = None
  _globals['_TILE_FEATURE'].fields_by_name['radii']._serialized_options = b'\020\001'
  _globals['_TILE']._serialized_start=46
  _globals['_TILE']._serialized_end=762
  _globals['_TILE_VALUE']._serialized_start=101
  _globals['_TILE_VALUE']._serialized_end=274
  _globals['_TILE_FEATURE']._serialized_start=277
  _globals['_TILE_FEATURE']._serialized_end=474
  _globals['_TILE_LAYER']._serialized_start=477
  _globals['_TILE_LAYER']._serialized_end=659
  _globals['_TILE_GEOMTYPE']._serialized_start=661
  _globals['_TILE_GEOMTYPE']._serialized_end=762
# @@protoc_insertion_point(module_scope)
